<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Plano de Testes  Tarefa</name>
   <tag></tag>
   <elementGuidId>1a9aff3e-d07b-4e35-a474-dee4a87be671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=''])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#module-1179200 > div.activity-item.focus-control > div.activity-grid > div.activity-name-area.activity-instance.d-flex.flex-column.mr-2 > div.activitytitle.media.modtype_assign.position-relative.align-self-start > div.media-body.align-self-center > div.activityname > a.aalink.stretched-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Plano de Testes Tarefa&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>23fc4949-d9e8-4854-8f5c-9dc9a60ec8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.moodle.udesc.br/mod/assign/view.php?id=1179200</value>
      <webElementGuid>35b66eee-2655-486b-938e-e590e430b27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> aalink stretched-link</value>
      <webElementGuid>2c82796e-768c-4fd0-b44b-e31d5f39aeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Plano de Testes  Tarefa    </value>
      <webElementGuid>2fe7d852-0c78-488a-89b9-74bb0edf41e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module-1179200&quot;)/div[@class=&quot;activity-item focus-control&quot;]/div[@class=&quot;activity-grid&quot;]/div[@class=&quot;activity-name-area activity-instance d-flex flex-column mr-2&quot;]/div[@class=&quot;activitytitle media  modtype_assign position-relative align-self-start&quot;]/div[@class=&quot;media-body align-self-center&quot;]/div[@class=&quot;activityname&quot;]/a[@class=&quot;aalink stretched-link&quot;]</value>
      <webElementGuid>a7738ff2-0f1e-46ba-bdda-4d3eae33f953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=''])[4]</value>
      <webElementGuid>4c0c8ab5-f7ab-4b22-9d0f-9546ea44d033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='module-1179200']/div/div[2]/div/div/div/div/a</value>
      <webElementGuid>5c2eb2c8-ccbc-46f1-9cf7-dd6ac7a3eed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecionar atividade Plano de Testes'])[1]/following::a[2]</value>
      <webElementGuid>628bd08c-e374-4e54-806d-6bc0442f2a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marcar como feito'])[4]/following::a[2]</value>
      <webElementGuid>d2af0da0-6782-4bf0-90f5-304585f0039b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.moodle.udesc.br/mod/assign/view.php?id=1179200')])[3]</value>
      <webElementGuid>ab2289e4-7681-49f3-bc1f-dd201bf2f60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div[2]/div/div/div/div/a</value>
      <webElementGuid>3472a75d-f411-44e7-a52e-b4b9f889c0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.moodle.udesc.br/mod/assign/view.php?id=1179200' and (text() = '        Plano de Testes  Tarefa    ' or . = '        Plano de Testes  Tarefa    ')]</value>
      <webElementGuid>41a27b13-cec7-4393-9527-ad1633922570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
