<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Acessar</name>
   <tag></tag>
   <elementGuidId>546e4fc3-2eeb-4f91-873e-82088bb2acbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='usernavigation']/div[4]/div/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.login.pl-2 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Navegação no site&quot;i >> internal:role=link[name=&quot;Acessar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cce47d26-2055-4dc4-aa8e-93b2217edf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.moodle.udesc.br/login/index.php</value>
      <webElementGuid>93a33b00-40c9-4407-9855-1d2635bbec18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acessar</value>
      <webElementGuid>8ec669bb-68ae-463d-93b9-9068251817d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernavigation&quot;)/div[@class=&quot;d-flex align-items-stretch usermenu-container&quot;]/div[@class=&quot;usermenu&quot;]/span[@class=&quot;login pl-2&quot;]/a[1]</value>
      <webElementGuid>9ab3b32a-715f-424c-ab19-2cda87ab67df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='usernavigation']/div[4]/div/span/a</value>
      <webElementGuid>8b875c1f-70ec-4fdb-8a08-01df95abcef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Acessar')]</value>
      <webElementGuid>cdc8705a-4566-42f6-b9c3-958e70fb3d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English ‎(en)‎'])[1]/following::a[2]</value>
      <webElementGuid>787155cc-06d7-4e09-84fe-9cbf86d4ba47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Página inicial'])[2]/preceding::a[1]</value>
      <webElementGuid>730066f3-7405-4515-a9b4-1cabaaf31c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minhas salas'])[2]/preceding::a[2]</value>
      <webElementGuid>9eebfedb-385f-49c3-b14d-073cae909915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acessar']/parent::*</value>
      <webElementGuid>34ae2cab-1821-46ab-b31a-609bf4ceb08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.moodle.udesc.br/login/index.php')]</value>
      <webElementGuid>ab5e2afc-ad18-4728-8934-8b491a2786aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>3d1275b0-fa41-4d09-8a01-ed66941ee017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.moodle.udesc.br/login/index.php' and (text() = 'Acessar' or . = 'Acessar')]</value>
      <webElementGuid>fb852474-8b86-422e-b31a-1ab1e81edfbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
