<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_000  059Assista o vdeo completoAo vivo</name>
   <tag></tag>
   <elementGuidId>37ebd71f-7003-427b-b091-d7374e4c20f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inline-preview-player']/div[20]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ytp-inline-preview-scrim</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#media-container-link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ea03500-f4cf-4172-9f51-a9ef63476cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-inline-preview-scrim</value>
      <webElementGuid>d47ed9b7-ee2c-4193-8b48-b9a0f87f8359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0:00 / 0:59•Assista o vídeo completoAo vivo</value>
      <webElementGuid>65fc6a85-b3fc-492a-9b68-94bb509fde7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inline-preview-player&quot;)/div[@class=&quot;ytp-inline-preview-ui&quot;]/div[@class=&quot;ytp-inline-preview-scrim&quot;]</value>
      <webElementGuid>63da6ef4-02d3-48b3-998e-c88cf1fa7ad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inline-preview-player']/div[20]/div</value>
      <webElementGuid>6216c668-6710-456e-915b-1e844b839766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='•'])[90]/following::div[2]</value>
      <webElementGuid>d2e8bf2f-737f-4e83-9b29-58b73e8707cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saiba mais'])[2]/following::div[53]</value>
      <webElementGuid>90709f30-8744-4065-9c21-bd27e75d8c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/ytd-player/div/div/div[20]/div</value>
      <webElementGuid>5ba52510-698a-4823-a8f3-5c49b1162ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0:00 / 0:59•Assista o vídeo completoAo vivo' or . = '0:00 / 0:59•Assista o vídeo completoAo vivo')]</value>
      <webElementGuid>3fc0f644-9301-41ab-957d-2119c617dfb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
